### ISSUE TITLE
New exporter does not have client and filesystem level metrics 

### ISSUE THREAD

**Issue by jmg011** [PureStorage-OpenConnect/pure-fb-openmetrics-exporter#1] opened 2022-02-15 21:30 UTC
I have set up the new exporter for one of the pure arrays. I noticed that all these client and filesystem level metrics are not available in the new exporter. Not available as part of any other new metrics either. 

These are important filesystem and client level metrics. Can you please provide more information on why these are deprecated from the new exporter and if there is any plan to add these back?

purefb_client_performance_iops
purefb_client_performance_latency_usec
purefb_client_performance_opns_bytes
purefb_client_performance_throughput_bytes
purefb_filesystem_user_usage_bytes
purefb_filesystem_group_usage_bytes
purefb_filesystem_performance_iops
purefb_filesystem_performance_latency_usec
purefb_filesystem_performance_opns_bytes
purefb_filesystem_performance_throughput_bytes

**Comment by genegr** [comment] 2022-02-16 15:29
Those metrics you are looking for are deemed the most expensive ones in terms of slow response time. For that reason I have defined two specific endpoints that can be used to grab the related info:

http://<fb-exporter>:<port>/metrics/clients

and

http://<fb-exporter>:<port>/metrics/usage

The exporter also reports those when invoked without any specific endpoint, like this

http://<fb-exporter>:<port>/metrics

In both cases you should consider that the response time may very considerably, from something in between 15 and 120 sec, depending on the cardinality of clients and filesystems, therefore you may have to increse the scraping interval timeout for Prometheus and also for the exporter, otherwise the whole array will be marked as down by Prometheus.

**Comment by genegr** [comment] 2022-02-16 23:54
Hi @jmg011,
The metrics have been renamed from the previous version of the exporter in order to reflect the name of the corresponding API endpoints. Also I was wrong with my previous answer. The file systems metrics are included in those reported by the /metrics/array and by the /metrics endpoints and their names are these:


purefb_file_systems_space_data_reduction_ratio
purefb_file_systems_space_bytes
purefb_file_systems_performance_latency_usec
purefb_file_systems_performance_throughput_iops
purefb_file_systems_performance_bandwidth_bytes
purefb_file_systems_performance_average_bytes
purefb_file_system_links_lag_msec

The file system usage metrics are instead reported by the /metrics/usage endpoint and are the following

purefb_file_system_usage_users_bytes
purefb_file_system_usage_groups_bytes

Also we have noticed that the current 0.8.1 image published on quay.io has some issues when run on docker engine so it is suggested to use the 0.8.2 which now defaults to the base docker-alpine image

**Comment by jmg011** [comment] 2022-02-21 22:58
@genegr - I used 0.8.2 image and I still do not see those file system level metrics which are renamed. Can you please confirm that this is the correct image? quay.io/purestorage/pure-fb-ome:0.8.2

**Comment by jmg011** [comment] 2022-02-25 17:58
Hi @genegr - Any update on this?

**Comment by genegr** [comment] 2022-02-27 02:56
Hi @jmg011 - There is a new image quay.io/purestorage/pure-fb-ome:0.8.2, that corresponds to the current release 0.8.3 and that  is based on Sanic instead than Flask+Gunicorn. Anyhow I can confirm the file system metrics are retrived in this and all the previous version of the exporter, at least for the arrays that are on Purity versions 3.2.x. It might instead be the case the file system specific metrics are not retrieved for other less recent Purity releases because they are not available to the REST APIs.

**Comment by jmg011** [comment] 2022-03-02 21:47
@genegr Thank you. Let me try this new image and see if I can get those metrics. We have 3.2.x so I should be able to get it. I will get back if I still see an issue.

**Comment by jmg011** [comment] 2022-03-03 01:48
@genegr I tested with this quay.io/purestorage/pure-fb-ome:0.8.2 image

**Configuration:** 

purity/FB version="3.2.6"
scrape interval: 2m
scrape timeout: 2m

No timeouts with 2m interval 

**scrapped end points:** _(successful scraping, no failures)_

_(tested without /metrics as well)_

/metrics
/metrics/clients
/metrics/usage
/metrics/array

I see only below 4 filesystem metrics. Can we have a working session to debug this? I can request the account manager to set up a meeting. 

![image](https://user-images.githubusercontent.com/89614353/156480540-c4df2a8c-1ebd-49ce-84d6-05c76f6f5c84.png)

**Comment by genegr** [comment] 2022-03-07 10:06
@jmg011 Sure thing. We can certainly arrange a session for troubleshooting your current setup. One thing that we have noticed is that there are some differencies between 3.3.x and 3.2.x (and even between 3.3.1 and 3.3.0). In addition to those, there is also a weird issue with the py-pure-client that generates a leak of file descriptors and I am trying to fix  that by swithcing to the 'request' python module until our API client library gets fixed.

**Comment by jmg011** [comment] 2022-03-29 20:06
@genegr - Can you point me to the exporter for Pure Block Storage?

**Comment by sdodsley** [comment] 2022-03-29 20:18
@jmg011 you can find it here: https://github.com/PureStorage-OpenConnect/pure-fa-openmetrics-exporter
Note that this is in beta and that @genegr is currently on sick leave for a few weeks, so bug fixes may take longer to be addressed

**Comment by jmg011** [comment] 2022-03-29 23:46
@sdodsley Thank you. Can you verify this syntax? The docker fails to run with this error:

unrecognized arguments: pure_fa_ome:create_app(disable_ssl_warn=True)

docker run -d -p 9491:9491 --name pure-exporter-fa-ver1 quay.io/purestorage/pure-fa-ome 'pure_fa_exporter:create_app(disable_ssl_warn=True)'

**Comment by jmg011** [comment] 2022-03-30 00:48
@sdodsley Thank you. I ran the exporter on docker. Disabled SSL check.

The logs say: 

[2022-03-30 00:38:32 +0000] [1] [INFO] packages: sanic-routing==0.7.2
[2022-03-30 00:38:32 +0000] [1] [INFO] Starting worker [1]


But when I try to access the end-point /metrics, it does not return anything. It says site cannot be reached. I double checked on the port numbers and everything. 

http://<FQDN>:9491/metrics  

What could be the possible issue?

**Comment by jmg011** [comment] 2022-04-05 21:31
@sdodsley @genegr - Hi Any update on this?

**Comment by sdodsley** [comment] 2022-04-06 03:29
@jmg011 there will be a delay to responding as @genegr has had a medical emergency and will be offline for a number of weeks.
I will try and get someone else to look at this in the meantime.

**Closed** 2022-09-04 07:07 UTC
